let playlist = [
  {
    playlistID: 1,
    playlist_name: "Morning Motivation",
    playlist_author: "Emily Chen",
    playlist_art: "assets/img/Morning Motivation.jpg",
    playlist_likes: 5,
    songs: {
      "Wake Me Up": {
        duration: "3:44",
        author: "Avicii",
        album: "True",
        img: "assets/img/Wake Me Up.jpg",
      },
      "Can't Stop": {
        duration: "5:11",
        author: "Red Hot Chili Peppers",
        album: "By the Way",
        img: "assets/img/RedHotChiliPeppersCantStop.jpg",
      },
      "Uptown Funk": {
        duration: "4:38",
        author: "Mark Ronson ft. Bruno Mars",
        album: "Uptown Special",
        img: "assets/img/Uptown Funk.jpg",
      },
      Happy: {
        duration: "3:53",
        author: "Pharrell Williams",
        album: "G I R L",
        img: "assets/img/Happy PW.jpg",
      },
    },
  },
  {
    playlistID: 2,
    playlist_name: "Relaxing Evening",
    playlist_author: "David Lee",
    playlist_art: "assets/img/beachalbum.jpg",
    playlist_likes: 10,
    songs: {
      "River Flows in You": {
        duration: "3:38",
        author: "Yiruma",
        album: "First Love",
        img: "assets/img/beachalbum.jpg",
      },
      Weightless: {
        duration: "4:28",
        author: "Marconi Union",
        album: "Gravity",
        img: "assets/img/Weightless.jpg",
      },
      "Clair de Lune": {
        duration: "4:55",
        author: "Claude Debussy",
        album: "Preludes, Book 1",
        img: "assets/img/Clair de Lune.jpg",
      },
      "Moonlight Sonata": {
        duration: "5:23",
        author: "Ludwig van Beethoven",
        album: "Piano Sonata No. 14",
        img: "assets/img/Moonlight.jpg",
      },
    },
  },
  {
    playlistID: 3,
    playlist_name: "Workout Mix",
    playlist_author: "Sarah Taylor",
    playlist_art: "assets/img/Workout mix.jpg",
    playlist_likes: 15,
    songs: {
      "Eye of the Tiger": {
        duration: "3:59",
        author: "Survivor",
        album: "Eye of the Tiger",
        img: "assets/img/Eye Of Tiger.jpg",
      },
      "Lose Yourself": {
        duration: "5:26",
        author: "Eminem",
        album: "8 Mile: Music from and Inspired by the Motion Picture",
        img: "assets/img/Lose_Yourself.jpg",
      },
      "We Will Rock You": {
        duration: "2:28",
        author: "Queen",
        album: "News of the World",
        img: "assets/img/We Will Rock You.png",
      },
      Unstoppable: {
        duration: "3:59",
        author: "Sia",
        album: "This Is Acting",
        img: "assets/img/Unstoppable.jpg",
      },
    },
  },
  {
    playlistID: 4,
    playlist_name: "Throwback Thursday",
    playlist_author: "Michael Brown",
    playlist_art: "assets/img/TBT Album.png",
    playlist_likes: 20,
    songs: {
      "I Want It That Way": {
        duration: "3:33",
        author: "Backstreet Boys",
        album: "Millennium",
        img: "assets/img/I Want It That Way.jpg",
      },
      Waterfalls: {
        duration: "4:39",
        author: "TLC",
        album: "CrazySexyCool",
        img: "assets/img/Waterfalls.jpg",
      },
      "No Scrubs": {
        duration: "3:38",
        author: "TLC",
        album: "FanMail",
        img: "assets/img/No-Scrubs.jpg",
      },
      "Bye Bye Bye": {
        duration: "3:19",
        author: "NSYNC",
        album: "No Strings Attached",
        img: "assets/img/Bye-BB.jpg",
      },
    },
  },
  {
    playlistID: 5,
    playlist_name: "Beatopia",
    playlist_author: "Beabadoobee",
    playlist_art: "assets/img/Beatopia.png",
    playlist_likes: 12,
    songs: {
      "the perfect pair": {
        duration: "2:58",
        author: "Beabadoobee",
        album: "Beatopia",
        img: "assets/img/Beatopia.png",
      },
      "Ripples": {
        duration: "4:06",
        author: "Beabadoobee",
        album: "Beatopia",
        img: "assets/img/Beatopia.png",
      },
      "See you Soon": {
        duration: "3:27",
        author: "Beabadoobee",
        album: "Beatopia",
        img: "assets/img/Beatopia.png",
      },
      "Lovesong": {
        duration: "4:06",
        author: "Beabadoobee",
        album: "Beatopia",
        img: "assets/img/Beatopia.png",
      },
    },
  },
  {
    playlistID: 6,
    playlist_name: "Utopia",
    playlist_author: "Travis Scott",
    playlist_art: "assets/img/Utopia.png",
    playlist_likes: 76,
    songs: {
      "HYAENA": {
        duration: "4:55",
        author: "Travis Scott",
        album: "Preludes, Book 1",
        img: "assets/img/Utopia.png",
      },
      "MY EYES": {
        duration: "5:23",
        author: "Travis Scott",
        album: "UTOPIA",
        img: "assets/img/Utopia.png",
      },
      "THANK GOD": {
        duration: "4:07",
        author: "Travis Scott",
        album: "UTOPIA",
        img: "assets/img/Utopia.png",
      },
      "GOD'S COUNTRY": {
        duration: "2:08",
        author: "Travis Scott",
        album: "UTOPIA",
        img: "assets/img/Utopia.png",
      },
      "MODERN JAM": {
        duration: "4:16",
        author: "Travis Scott",
        album: "UTOPIA",
        img: "assets/img/Utopia.png",
      },
      "FE!N": {
        duration: "3:12",
        author: "Travis Scott",
        album: "UTOPIA",
        img: "assets/img/Utopia.png",
      },
      "TIL FURTHER NOTICE": {
        duration: "5:15",
        author: "Travis Scott",
        album: "UTOPIA",
        img: "assets/img/Utopia.png",
      },
    },
  },
  {
    playlistID: 7,
    playlist_name: "Persona 4 Golden",
    playlist_author: "ATLUS",
    playlist_art: "assets/img/P4 Album2.jpg",
    playlist_likes: 33,
    songs: {
      "Pursuing My True Self": {
        duration: "1:26",
        author: "ATLUS",
        album: "P4 Golden",
        img: "assets/img/P4 Album.png",
      },
      "Signs Of Love": {
        duration: "3:23",
        author: "ATLUS",
        album: "P4 Golden",
        img: "assets/img/P4 Album.png",
      },
      "New Days": {
        duration: "2:17",
        author: "ATLUS",
        album: "P4 Golden",
        img: "assets/img/P4 Album.png",
      },
      "Your Affection": {
        duration: "2:08",
        author: "ATLUS",
        album: "P4 Golden",
        img: "assets/img/P4 Album.png",
      },
      "Reach Out To The Truth": {
        duration: "2:57",
        author: "ATLUS",
        album: "P4 Golden",
        img: "assets/img/P4 Album.png",
      },
      "Specialist": {
        duration: "2:12",
        author: "ATLUS",
        album: "P4 Golden",
        img: "assets/img/P4 Album.png",
      },
      "Youthful lunch": {
        duration: "5:15",
        author: "ATLUS",
        album: "P4 Golden",
        img: "assets/img/P4 Album.png",
      },
      "Castle": {
        duration: "2:38",
        author: "ATLUS",
        album: "P4 Golden",
        img: "assets/img/P4 Album.png",
      },
    },
  }
];
